### ISSUE TITLE
Error  There has been an unexpected error while calling npm-groovy-lint. please join the end of the logs in Output/GroovyLint 

### ISSUE THREAD

**Issue by ajay-kakumanu-ghub** [nvuillam/vscode-groovy-lint#108] opened 2021-04-07 20:42 UTC
Dear Team, 
iam getting the error 
" There has been an unexpected error while calling npm-groovy-lint. please join the end of the logs in Output/GroovyLint if the yiur t"
I have reported several times. still getting the issue, 
May i get some help ?
<img width="342" alt="error" src="https://user-images.githubusercontent.com/63850298/113931234-d6979600-97b7-11eb-9411-9497eeb21694.png">

![image](https://user-images.githubusercontent.com/63850298/113931142-bf58a880-97b7-11eb-9d1a-62778154dee4.png)

**Comment by mcgarrah** [comment] 2021-04-14 19:33
Same here. Do not know what I can add.

**Comment by bselladurai** [comment] 2021-04-21 20:38
![image](https://user-images.githubusercontent.com/82398078/115617919-fe125680-a2bf-11eb-860d-24f73d41fcc9.png)

**Comment by varnar** [comment] 2021-05-31 23:08
Same

**Comment by HeavyD-24** [comment] 2021-06-24 07:15
`Error running command extension.jenkins-jack.tree.pipeline.pullJobScript: Running the contributed command: 'extension.jenkins-jack.tree.pipeline.pullJobScript' failed.. This is likely caused by the extension that contributes extension.jenkins-jack.tree.pipeline.pullJobScript.
`

**Comment by Sunchock** [comment] 2022-01-28 12:29
Same here, when I first installed this extension, i've got this new warning in host extension logs
`[2022-01-28 13:25:49.371] [exthost] [warning] DiagnosticCollection with name 'GroovyLint' does already exist.`

**Comment by nvuillam** [comment] 2023-12-17 09:01
@ajay-kakumanu-ghub   this is fixed in newest release v3.0.0, thanks to the great job of @stevenh :)

Please can you confirm it works well for your case now ?
- If yes, please rate the app -> https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint&ssr=false#review-details
- If not, please reopen the issue and we'll check :)

**Closed by nvuillam** 2023-12-17 09:01 UTC

**Comment by kkossev** [comment] 2023-12-17 09:16
I can confirm the issue is fixed in release v3.0.0 - thank you!

**Comment by nvuillam** [comment] 2023-12-17 09:40
@kkossev many thanks for your feedback :)
